name: Rastreador de Precios Automático

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar librerías
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib playwright

    - name: Instalar navegadores para Playwright
      run: |
        playwright install chromium
        playwright install-deps chromium

    - name: Ejecutar el rastreador
      run: python rastreador.py

    - name: Subir y guardar archivos en el repositorio
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git status
        git add -f historial_precios.csv grafico_precios.png
        git commit -m "Actualizar CSV y Gráfica de precios"
        git push origin main
